# Les séries de Taylor {#taylor}

## Les polynômes de Taylor et de MacLaurin

De tous les types de fonctions, les fonctions polynomiales sont celles qui se dérivent et s'intègrent le plus facilement. De plus, si leur degré est inférieur ou égal à 5, des formules permettent de trouver facilement leurs zéros. Pour ces raisons, l'écriture d'une fonction $f(x)$ sous la forme d'un polynôme de degré $n$, $P_n(x)$, nous permet de l'étudier aisément. Cependant, en écrivant une fonction sous la forme d'un polynôme, nous obtenons une approximation.

L'approche de Taylor et de MacLaurin est couramment utilisée pour transformer une fonction en polynôme.

### Les polynômes de MacLaurin

Pour savoir de quelle manière exprimer une fonction $f(x)$ sous la forme d'un polynôme, nous étudierons un cas particulier des polynômes de Taylor, soit les polynômes de MacLaurin.

```{definition name = "Polynôme de Maclaurin"}
Soit $f(x)$ une fonction dérivable au moins $n$ fois. Le __polynôme de MacLaurin__ de degré $n$, $P_n(x)$, de la fonction $f(x)$ est un polynôme satisfaisant les conditions suivantes:
\begin{align}
\begin{split}
f(0) &= P_n(0) \\
\left.\dfrac{d^k f}{dx^k}\right|_{x=0} &= \left.\dfrac{d^k P_n}{dx^k}\right|_{x=0}, \quad \text{pour } k\in\{1,\ldots,n\}
\end{split}
\end{align}
```

Les deux conditions suivantes permettent de construire le polynôme de MacLaurin pour une fonction $f(x)$ quelconque. Nous savons qu'un polynôme de degré $n$ s'écrit de la façon suivante:

\begin{align*}
P_n(x)=a_0+a_1x+a_2x^2+...+a_{n-1}x^{n-1}+a_nx^n
\end{align*}

Pour trouver les coefficients $a_k$, nous devons obtenir les dérivées successives de $P_n(x)$. Ainsi:

\begin{align}
\begin{split}
P_n(x) &= a_0+a_1x+a_2x^2+...+a_{n-1}x^{n-1}+a_nx^n \\
P_n^{(1)}(x) &= 1a_1+2a_2x+3a_3x^2+...+(n-1)a_{n-1}x^{n-2}+na_nx^{n-1} \\
P_n^{(2)}(x) &= 2\cdot 1a_2+3\cdot 2a_3x+...+(n-1)(n-2)a_{n-1}x^{n-3}+n(n-1)a_nx^{n-2} \\
P_n^{(3)}(x) &= 3\cdot 2\cdot 1a_3+...+(n-1)(n-2)(n-3)a_{n-1}x^{n-4}+n(n-1)(n-2)a_nx^{n-3}
\end{split}
\end{align}
et ainsi de suite.

Par définition, nous savons que $f(0)=P_n(0)$. Ainsi:

\begin{align}
\begin{split}
f(0)&=P_n(0) \\
f(0) &= a_0+a_1(0)+a_2(0)^2+...+a_{n-1}(0)^{n-1}+a_n(0)^n \\
f(0)&=a_0
\end{split}
\end{align}

De même, nous savons que $f^{(1)}(0)=P_n^{(1)}(0)$. Ainsi:

\begin{align}
\begin{split}
f^{(1)}(0)&=P_n^{(1)}(0)\\
f^{(1)}(0)&=1a_1+2a_2(0)+3a_3(0)^2+...+(n-1)a_{n-1}(0)^{n-2}+na_n(0)^{n-1} \\
f^{(1)}(0)&=1a_1  \\
\dfrac{f^{(1)}(0)}{1}&=a_1
\end{split}
\end{align}

De la même façon, nous savons que $f^{(2)}(0)=P_n^{(2)}(0)$. Ainsi:

\begin{align}
\begin{split}
f^{(2)}(0)&=P^{(2)}_n(0)\\
f^{(2)}(0)&=2\cdot 1a_2+3\cdot 2a_3(0)+\ldots+(n-1)(n-2)a_{n-1}(0)^{n-3}+n(n-1)a_n(0)^{n-2} \\
f^{(2)}(0)&=2\cdot 1a_2  \\
\dfrac{f^{(2)}(0)}{2\cdot 1}&=a_2
\end{split}
\end{align}

D'une manière générale, nous trouvons:

\begin{align}
\begin{split}
a_k &= \dfrac{1}{k\cdot (k-1)\cdot ...\cdot 3\cdot 2\cdot 1}f^{(k)}(0) \\
&= \dfrac{f^{(k)}(0)}{k!}
\end{split}
\end{align}

```{remark, name = "Factorielle"}
La factorielle d'un nombre entier $k$ positif, notée $k!$, est égale à:
\begin{equation*}
k! = k(k-1)(k-2)\cdot\ldots\cdot 3\cdot 2\cdot 1
\end{equation*}
Et par définition $0!=1$.
```

Nous obtenons donc une équation pour déterminer le polynôme de MacLaurin d'une fonction.

```{definition, name = "Polynôme de MacLaurin"}
Soit $f(x)$ une fonction dérivable au moins $n$ fois en $x=0$. Le __polynôme de MacLaurin__ de degré $n$, $P_n(x)$, est donné par:
\begin{align*}
P_n(x)&=\sum_{k=0}^n\dfrac{f^{(k)}(0)}{k!}x^k=f(0)+f^{(1)}(0)x+\dfrac{f^{(2)}(0)}{2!}x^2+...+\dfrac{f^{(n)}(0)}{n!}x^n
\end{align*}
```

```{example}
Trouvez les polynômes de MacLaurin de degrés 1, 2 et 3 de $f(x)=e^x$.
\vspace*{8cm}
```

```{example}
Trouvez les polynômes de MacLaurin de degrés 1, 2 et 3 de $f(x)=sin(x)$.
\vspace*{8cm}
```

### Les polynômes de Taylor

Les polynômes de Maclaurin utilisent l'évaluation des dérivées successives de la fonction $f(x)$ en $x=0$. Il est par contre possible de généraliser ces polynômes en évaluant les dérivées successives de la fonction $f(x)$ en $x=a$, avec  $a\in \text{dom} f$. C'est ce que nous appelons les polynômes de Taylor.

```{definition, name = "Polynôme de Taylor"}
Soit $f(x)$ une fonction dérivable au moins $n$ fois en $x=a$. Le __polynôme de Taylor__ de degré $n$, $P_n(x)$, est donné par:
\begin{align*}
P_n(x)&=\sum_{k=0}^n\dfrac{f^{(k)}(a)}{k!}(x-a)^k\\
&=f(a)+f^{(1)}(a)(x-a)+\dfrac{f^{(2)}(a)}{2!}(x-a)^2+...+\dfrac{f^{(n)}(a)}{n!}(x-a)^n
\end{align*}
```

```{example}
Trouvez le polynôme de Taylor de $f(x)=\ln(x)$ de degré $4$ autour de $x=1$.
\vspace*{8cm}
```

### Le reste de Taylor-Lagrange

Les polynômes de Taylor sont des approximations d'une fonction, ce qui signifie qu'une erreur est commise. Le théorème suivant nous permet de quantifier l'erreur commise, c'est-à-dire $f(x)-P_n(x)$.

```{theorem, name = "Le reste de Taylor-Lagrange"}
Soit $f(x)$ une fonction dérivable au moins $n+1$ fois sur l'intervalle $I=[a,x]$ (si $x>a$) ou $I=[x,a]$ (si $x<a$). L'erreur commise $E_n(x)$ par l'approximation de $f(x)$ par $P_n(x)$ est donnée par:
\begin{align*}
|f(x)-P_n(x)|=|E_n(x)|=\left\vert\dfrac{f^{(n+1)}(\xi(x))}{(n+1)!}(x-a)^{(n+1)}\right\vert
\end{align*}
avec $\xi(x)\in I$.
```
```{proof}
La démonstration est plus avancée que le niveau de ce livre.
```

Comme la valeur $\xi(x)$ est rarement connue, nous utiliserons plutôt une borne sur l'erreur:

\begin{align*}
	|E_n(x)|=|f(x)-P_n(x)|&=\left\vert\dfrac{f^{(n+1)}(\xi(x))}{(n+1)!}(x-a)^{n+1}\right\vert\\
	|f(x)-P_n(x)| &\leq \left\vert\dfrac{M}{(n+1)!}(x-a)^{n+1}\right\vert,
\end{align*}
où $M=\text{max}_{x\in I}\left\vert f^{(n+1)}(x) \right\vert$.

## GeoGebra

<meta name=viewport content="width=device-width,initial-scale=1">
<script type="text/javascript" src="https://cdn.geogebra.org/apps/deployggb.js"></script>
<script type="text/javascript">
var parameters = {
"id":"ggbApplet",
"material_id":"jg2qjmar",
"width":800,
"height":600,
"showToolBar":true,
"borderColor":null,
"showMenuBar":true,
"allowStyleBar":true,
"showAlgebraInput":true,
"enableLabelDrags":false,
"enableShiftDragZoom":true,
"capturingThreshold":null,
"showToolBarHelp":false,
"errorDialogsActive":true,
"showTutorialLink":true,
"showLogging":true,
"useBrowserForJS":false,
"perspective":"AG"};

var applet = new GGBApplet(parameters, '5.0', 'applet_container');
window.onload = function() { applet.inject('applet_container'); updateHelp('AG');}
</script>
<div id="applet_container"></div>
